# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff548a9d9ba89614d040fe1bd063ae3c4d8ed3d640a63a354232bb5a0f70f6728f5cd0b84b7a1f3b4f5103ca6d6865aa7e0ca022e8457b0ce6f987e42845a29a

test:
  secret_key_base: 115347cfd4091f9fdfa44bcc7608d13d5d0ae69050bea8dfba9697840431129538c6c82408dcf4a75fdd3a52c76dfc67348c0a2410bc78f02cbac1670b42a8ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
