# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb048ef1d237e979f37b36144b2052b73577870a5647d818ccf9b1675f3b985f25c4305cc40e8f290dcf2c09a5d3f8791af402bff9c0a166d68646ff6acaf5f5

test:
  secret_key_base: 1897aabb4d60d5263d826c2c566484132d75ba2cd61d567e2052ea27704d690e1572255c6c0571d3613ea9d0533faa0371c2d457e29dff898f09bc7b9fdec667

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
